spring.application.name=api-

# Puerto de tu servidor Java
server.port=8080

# URL de tu IA en Render (Asegúrate de no poner el '/' al final)
python.api.url=https://modeloiacybersentinel.onrender.com

